- Cargo.lock
this PR was intended to fix #8 but after checking, I found that this crate is already on 2021.. so I decided to run a `cargo update` in order to contribute at least something :)
> chore(deps): bump versions

- codecov.yml
This is to ensure that trivial decreases in code coverage don't fail the pipeline.
> chore(codecov): add codecov config

- extra/systemd/rustypaste.env
- extra/systemd/rustypaste.service
- extra/systemd/rustypaste.sysusers
- extra/systemd/rustypaste.tmpfiles
Add systemd files to serve files from /var/lib/rustypaste, automatic
user creation via systemd-sysusers and AUTH_TOKEN configuration via
rustypaste.env in /etc/rustypaste/rustypaste.env.
implements #16
> chore(systemd): add systemd service files

- config.toml
It is an expensive operation to do on slower hardware and can take unreasonable amount of time for bigger files
> chore(config): do not check for duplicate files by default

- config.toml
- fixtures/test-server-landing-page/config.toml
- fixtures/test-server-landing-page/test.sh
- src/config.rs
- src/server.rs
Fixes orhun/rustypaste#13
The default landing page is set as a const in the binary, but is configurable with the server.landing_page key. Should the key be in another section (i.e. not `[server]`? Handling is added for when the config file doesn't have any landing page. I updated the default config.toml.
> feat(server): add landing page

- config.toml
- src/config.rs
- src/server.rs
Configurable and behind authentication. By default disabled.
Fixes: #27
Signed-off-by: Leonidas Spyropoulos <artafinde@archlinux.org>
> feat(server): expose version as endpoint

- config.toml
As mentioned on the release notes the default should have been to not expose the `/version` config.
This is affecting Archlinux release.
> fix(config): don't expose version endpoint in default config

- .github/workflows/shuttle.yml
- Cargo.lock
- Cargo.toml
this allows reusing the openssl present on a distro already, and takes a release build with it from 5.5 to 4.7mb
> feat(deps): allow using openssl for tls

- config.toml
- fixtures/test-server-landing-page/config.toml
- shuttle/config.toml
- src/config.rs
- src/server.rs
I realized that I don't need to implement this in a repo at all.  The user can already set a custom landing page in the config.  The only thing I needed to change was the content type so that the browser rendered it.  This makes the landing page content type available in the configuration.
Fixes #39
> feat(server): allow configuring the content type for landing page

- README.md
- fixtures/test-oneshot-url/config.toml
- fixtures/test-oneshot-url/test.sh
- src/main.rs
- src/paste.rs
- src/server.rs
- src/util.rs
Fix #38 
This adds support for a new paste type `OneshotUrl`.
- Add enum `PasteType::OneshotUrl`.
- Set content disposition to `oneshot_url`
- Add test to ensure that a oneshot_url is not found after making the first request
PS: It's totally possible I might have missed something. Honestly I don't fully understand the logic for how the files get deleted but I tried to follow the existing `oneshot` design (which seems to just rename the file with current timestamp so I did the same). The test I added does seem to work so hopefully this does the job.
> feat(server): support one shot URLs

- README.md
These suffixes are also supported in the `config.toml`.
---
The duration is not consistently used. e.g. in the `config.toml` it says `default_expiry = "1h"` and not `default_expiry = "1hours"` as it is shown in the README. Also, I think people are rather used to single character duration units like s, m, h, d, w, y.
So I believe listing all supported units is useful for usability and consistency.
> docs(readme): list all supported units for expiry

- src/main.rs
- src/server.rs
Behind a reverse proxy, the log entries always showed the IP address of the reverse proxy. With this change the real IP address of the client is shown. Since the IP address is only used for info in the log, there are no security implications.
closes #54
> feat(server): honor X-Forward-* headers

- fixtures/test-server-landing-page-file/config.toml
- fixtures/test-server-landing-page-file/test.sh
- src/config.rs
- src/server.rs
As contemplated in #52, this PR adds another config option `landing_page_file`.
If the file cannot be found, it will fall back to `landing_page`.
Tested: manually with 
- relative path
- absolute path
- file not found
- neither `landing_page_file` or `landing_page` set
Issue #52 also talks aboutrefactoring and changing the example html landing_page, thus I am not sure whether this PR should close that issue.
> feat(server): support a file for the landing page

- src/server.rs
I noticed a little missing new line character after I ran command for testing how rustypaste works:
`curl http://localhost:8000/sweeping-tahr`
After that, server side returns:
`file is not found or expired :(` without new line character and terminal output looks bad.
> style(server): add new line character to 404 message

- README.md
- config.toml
- fixtures/test-file-upload/config.toml
- fixtures/test-file-upload/test.sh
- fixtures/test-random-suffix/config.toml
- fixtures/test-random-suffix/test.sh
- src/paste.rs
- src/random.rs
Unfortunately the current implementation does not retain multiple extensions. So if you upload `foo.tar.gz`, the resulting file will be `eu7f92x1.gz`.
This PR includes 2 changes:
- multiple extensions are retained (e.g. `eu7f92x1.tar.gz`)
- added an optional option `suffix_mode` (bool) to `random_url` (result: `foo.eu7f92x1.tar.gz`)
closes #41
> feat(server): add random suffix mode

- .github/PULL_REQUEST_TEMPLATE.md
When one wantes to use a code block in the changelog section it won't work, because it will end the previous block.
Adding another backtick solves the problem.
see above
created this PR with the changed text.
> chore(github): update the PR template about code blocks

- README.md
- config.toml
- fixtures/test-server-auth-multiple-tokens/config.toml
- fixtures/test-server-auth-multiple-tokens/test.sh
- src/auth.rs
- src/config.rs
- src/main.rs
- src/server.rs
This change supports the use of multiple authentication tokens.
Example:
```toml
[server]
auth_tokens = [
"super_secret_token1",
"super_secret_token2",
]
```
The previously used `AUTH_TOKEN` environment variable can still be used and will be evaluated as well.
Allow to give people access to an otherwise private rustypaste instance.
see https://github.com/orhun/rustypaste/discussions/79
- test cases (cargo test)
- fixtures 
- manual testing on a Linux test VM
````
- Add support for multiple auth tokens
Example:
```toml
[server]
auth_tokens = [
"super_secret_token1",
"super_secret_token2",
]
```
The previously used `AUTH_TOKEN` environment variable can still be used and will be evaluated as well.
````
> feat(server): support multiple auth tokens

- src/auth.rs
- src/server.rs
This change adds a newline character to the most prominent messages. 
This is a follow-up to #72 to make the output of the most prominent messages more consistent. 
Currently the output is not as legible as it could be:
```
[tessus@epsilon3 0 ~/data/tmp/rptest]$ curl https:/rptest.local/paste/version
unauthorized[tessus@epsilon3 0 ~/data/tmp/rptest]$ curl https:/rptest.local/paste/version -H "Authorization: token"
endpoint is not exposed[tessus@epsilon3 0 ~/data/tmp/rptest]$ curl https:/rptest.local/paste/not_available.txt
file is not found or expired :(
[tessus@epsilon3 0 ~/data/tmp/rptest]$ curl https:/rptest.local/paste/version -H "Authorization: token"
0.11.1[tessus@epsilon3 0 ~/data/tmp/rptest]$
```
Please note that I haven't added a new line character to all error messages, but only …
> style(server): add new line char to most prominent messages

- src/auth.rs
The server logs a sent token, if the token is not valid:
e.g.: `rpaste -a invalid_token -V`
```
[2023-08-13T19:24:30Z WARN  rustypaste::auth] authorization failure for a.b.c.d (header: invalid_token)
```
This change prints the token only in debug mode. In release mode the log entry will look like this:
```
[2023-08-13T19:24:30Z WARN  rustypaste::auth] authorization failure for a.b.c.d
```
fixes #111 
Let's say you use rpaste with the token in the config file (or curl with the auth_token as env var or in a file), but use different rustypaste servers. If you forget only once to add the `-a` flag (or add the header to curl), a production token for another instance will be logged.
- cargo test
- fixtures
- manual testing
````
- Don't log invalid token in release builds
````
> fix(server): don't log invalid token in release builds

- .github/workflows/cd.yml
- .github/workflows/ci.yml
This change replaces the unmaintained `action-rs/*` actions in the CI and CD workflows.
Get rid of warnings that show up in the action workflows.
Manual testing in the forked rustypaste repo.
````
- Replace unmaintained `action-rs/*` actions in the CI and CD workflows
````
> chore(ci): replace unmaintained actions

- config.toml
- examples/html_form.toml
- fixtures/test-duplicate-file-upload/config.toml
- fixtures/test-expiring-file-upload/config.toml
- fixtures/test-file-upload/config.toml
- fixtures/test-list-files/config.toml
- fixtures/test-oneshot-upload/config.toml
- fixtures/test-oneshot-url/config.toml
- fixtures/test-path-traversal/config.toml
- fixtures/test-random-suffix/config.toml
- fixtures/test-random-url/config.toml
- fixtures/test-remote-file-upload/config.toml
- fixtures/test-server-auth-multiple-tokens/config.toml
- fixtures/test-server-auth/config.toml
- fixtures/test-server-auto-deletion/config.toml
- fixtures/test-server-default-extension/config.toml
- fixtures/test-server-landing-page-file/config.toml
- fixtures/test-server-landing-page/config.toml
- fixtures/test-server-mime-blacklist/config.toml
- fixtures/test-server-mime-override/config.toml
- fixtures/test-server-payload-limit/config.toml
- fixtures/test-url-upload/config.toml
- shuttle/config.toml
- src/config.rs
- src/main.rs
- src/paste.rs
- src/random.rs
- src/server.rs
Currently, in order to turn random URL's off, you must have at least one `random_url` declaration with a type and enabled = `false`.
This PR makes the random_url config optional while deprecating the `enabled` field without breaking current configs.
Closes #121
- cargo test
- fixtures
- manual
````
- Make the `random_url` config optional
```toml
random_url = { type = "petname", words = 2, separator = "-" }
```
- Deprecate `enabled` field in `random_url`
````
> feat(server): improve random_url config handling

- Cargo.lock
- Cargo.toml
- Dockerfile
I didn't see that the bot already opened PRs for the crates. However it also contains an update to use a more recent `rustls` which uses the replacement (`rustls-webpki`) for the unmaintained `webpki` crate.
The updated crates require Rust >= 1.68.0, thus I updated the Dockerfile to use the latest Rust version (1.72.0).
Closes #125  #132  #133  #134
cargo test
fixtures
> chore(project): update crates and rustls deps

- README.md
- config.toml
- fixtures/test-file-delete/config.toml
- fixtures/test-file-delete/test.sh
- src/config.rs
- src/lib.rs
- src/server.rs
Add a DELETE endpoint guarded by a separate auth token array.
Closes #127 
Wrote a test case and tested manually.
````
- Change `Config.get_tokens` to `Config.get_auth_tokens` and update invocations.
- Add delete_tokens array to config and `get_delete_tokens` method to Config for retrieving delete tokens.
- Add DELETE endpoint that will remove files if a delete token is set and authorized by the request.
- Test for new DELETE endpoint
- Add DELETE_TOKEN_ENV for setting the delete tokens array from an ENV var.
````
-->
> feat(server): add delete endpoint

- fixtures/test-file-delete/test.sh
- src/server.rs
This PR just changes the srver resp9onse on successful file delete.
see https://github.com/orhun/rustypaste-cli/pull/54#discussion_r1314312071
cargo test
fixtures
manual testing
````
- Response message upon successful file deteletion
````
> refactor(server): change response to 'file deleted'

- Cargo.lock
- Cargo.toml
- src/auth.rs
- src/config.rs
- src/main.rs
- src/middleware.rs
- src/server.rs
resolves #161
Only changing `env_logger` into `tracing-subscriber`. It should support the same configuration with `RUST_LOG` (and more, if we convert from `log` to `tracing` later).
See #161.
Logging are usually not tested. If any test would be needed, could you give some pointers?
````
- Changes the logger formatter to `tracing-subscriber`
````
-->
> feat(log): switch to `tracing` for logging

- README.md
Add instructions for FreeBSD and related things to use rustypaste on that platform.
[I created a port](https://www.freshports.org/www/rustypaste/) a while ago, and recently created a Makejail (a Dockerfile-like file, but for AppJail) for rustypaste, so I think users can benefit from those things to use rustypaste on FreeBSD.
I have installed rustypaste using the official FreeBSD package and I have also tested rustypaste using Makejail on my notebook and on my production server where I currently host rustypaste.
I have tried a lot of combinations when using Makejail, much better described in the [repository](https://github.com/AppJail-makejails/rustypaste#customization) where Makejail is hosted.
For each rustypaste update I test the new and old features by simply modifying …
> docs(readme): add instructions for FreeBSD

- fixtures/test-expiring-file-upload/test.sh
- fixtures/test-list-files/test.sh
- fixtures/test-server-auto-deletion/test.sh
- fixtures/test-server-payload-limit/test.sh
Change fixtures to support macos as well as linux
- `sleep` doesn't work with time-units (e.g `sleep 1s`)
- there is no `fallocate`  (`dd if=/dev/random of=normalfile count=10000 bs=1024 status=none` used)
- string formatting with substitution works incorrectly `"$(curl -s -H "Authorization: $auth_token" localhost:8000/list | grep -o 'file_name' | wc -l)"` returns `"     3"`, so it's not equal to `"3"`
Fixtures works on macOS and should pass CI (on lunux)
````
- Support fixtures on macOS
````
> test(fixtures): support `fixtures` on `macOS`

- README.md
Just a clarification on how this works in the case of uninstalled tokens, for greater clarity and security
Discussed as part of #199, just to clarify the behavior
> docs(readme): explain behavior of unset `auth_tokens` and `delete_tokens`

- src/auth.rs
Iff one doesn't use auth tokens, their log is spammed with warning messages.
This change removes the warning message.
It also fixes a small typo.
Fixes #209
cargo test
fixtures
> fix(auth): remove excessive warning and typo

- src/server.rs
This change converts a path to a string.
```
<TIMESTAMP> INFO rustypaste::server: deleted file: Path("file-to-delete.txt")
```
```
<TIMESTAMP> INFO rustypaste::server: deleted file: "file-to-delete.txt"
```
- manually
- fixtures (no new tests)
- cargo test (no new tests)
````
- Improved server side logging when deleting a file
````
> fix(server): improve logging for deleted file

- .github/workflows/shuttle.yml
- dummy.txt
This change fixes the attempt to deploy on a PR.
see https://github.com/orhun/rustypaste/pull/210#issuecomment-1864888922
on my own repo
````
- Do not run shuttle deployment on Pull Requests
````
> ci(shuttle): fix deployment

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/paste.rs
- src/server.rs
- src/util.rs
Check that a joined path is still a child of the original path.
When joining paths, there's little protection against directory traversal. From testing, Actix seems to nicely sanitises these in the request, which is great, but it's still better to add a little protection.
Unit tests have been added, which pass.
> feat(server): do path joins more safely

- src/paste.rs
- src/server.rs
The file `https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg` was replaced by a different version on March 1st.
I checked, the old file still exists and the hash is the same, but unfortunately the `util::sha256_digest` seems to take the filename into account, because I tried to replace the link, but the hash changed in the rustypaste tests as well. When I check the hash on the commandline with `shasum`, it's actually the same though.
Since the hash changes either way, I just updated the hash, instead of link and hash.
fixes #253 
cargo test
fixtures
````
- update hash in tests, since the file changed at source
````
> test(upload): update the hash of the example file

- .github/workflows/ci.yml
Switching to `cargo-llvm-cov` due to the recent bugs with `cargo-tarpaulin`.
CI
> chore(ci): switch to cargo-llvm-cov for code coverage

- fixtures/test-file-upload-same-filename/test.sh
- fixtures/test-server-mime-blacklist/test.sh
- src/paste.rs
- src/server.rs
This change returns a more appropriate status code in 2 cases instead of a generic 500 code:
- UnsupportedMediaType (if the mime type is on the blacklist)
- Conflict (if the file already exists)
closes #261 
- cargo test
- fixtures
````
- Return appropriate HTTP status code instead of 500
````
> refactor(server): use more specific HTTP status codes

- README.md
- fixtures/README.md
- fixtures/test-expiring-file-upload/test.sh
- fixtures/test-fixtures.sh
- fixtures/test-server-auth-token-file/auth_file
- fixtures/test-server-auth-token-file/config.toml
- fixtures/test-server-auth-token-file/test.sh
- fixtures/test-server-delete-token-file/config.toml
- fixtures/test-server-delete-token-file/delete_file
- fixtures/test-server-delete-token-file/test.sh
- src/config.rs
- src/lib.rs
Add support for reading a list of newline separated tokens from a file
which path is being supplied through the following environment
variables:
- AUTH_FILE
- DELETE_FILE
Also add support for setting environment variables inside of fixtures through the optional `custom_env` function.
Also describe this new functionality in the readme.
Need a way to supply multiple auth token akin to `AUTH_TOKEN` due to agenix behaviour.
closes #338
Added UTs for file content parsing. File reading has not received any UT, but has been manually tested.
- Multiple authentication and deletion token parsing via a file to which `AUTH_FILE` and `DELETION_FILE` point. This file needs to be a newline separated list of strings. Whitespace is discarded.
> feat(server): add support for multiple auth tokens via env vars

- Dockerfile
The 'as' keyword should match the case of the 'from' keyword
FromAsCasing: 'as' and 'FROM' keywords' casing do not match
More info: https://docs.docker.com/go/dockerfile/rule/from-as-casing/
gh action produces a warning. see here: https://github.com/orhun/rustypaste/pull/343/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557
- waiting for the CI to complete.
````
- Dockerfile: The 'as' keyword should match the case of the 'from' keyword
````
> fix(docker): make keywords uppercase

- .github/workflows/ci.yml
Trying to get rid of deprecation notices in CI.
> chore(ci): switch to macOS 14

- fixtures/test-url-upload-override-filename/config.toml
- fixtures/test-url-upload-override-filename/test.sh
- src/paste.rs
- src/server.rs
I ran the filename header through the URL shortening route
This lets me use rustypaste to link to a specific link using a specified short name (for ergonomics).
Also fixes #40 by the by.
```
- Enable naming shortened URLs beyond using a random string or the text "url"
````
-->
> feat(server): allow named url shortening (#40)

- fixtures/test-fixtures.sh
```
$ ./test-fixtures.sh
[ok] test-duplicate-file-upload
[ok] test-expiring-file-upload
[ok] test-file-delete
[ok] test-file-upload
[ok] test-file-upload-override-filename
[ok] test-file-upload-same-filename
[ok] test-filename-replace
....
[ok] test-server-payload-limit
[ok] test-url-encode
[ok] test-url-upload
[ok] test-version-not-exposed
$
```
And it could be:
```
$ ./test-fixtures.sh
... everything from above without arguments....
$ ./test-fixtures.sh test-server-auth-multiple-tokens test-server-auth test-url-encode
[ok] test-server-auth-multiple-tokens
[ok] test-server-auth
[ok] test-url-encode
$
```
I was running tests for  #373 and it was taking long enough to warrant a fix.
Please see description for example run.
> test(fixtures): Ease testing just one fixture

- extra/systemd257+/rustypaste.sysusers
systemd v257 supports and recommends fully locked system accounts[1]
[1]: https://www.freedesktop.org/software/systemd/man/latest/sysusers.d.html#u
use fully locked system accounts
Recommendation from systmd v257 and above
https://github.com/systemd/systemd/blob/25a306f6c4d9b8596e25d7771802f005ebae91ba/NEWS#L822-L832
Not tested as this is downstream
- use fully locked sytem acounts on systemd > v257
> change: use fully locked system accounts

- src/server.rs
Fixes the following error in pipeline:
```
error: needless call to `as_bytes()`
--> src/server.rs:475:30
|
475 |             assert_eq!(size, expected.as_bytes().len() as u64);
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^ help: `len()` can be called directly on strings: `expected.len()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_as_bytes
= note: `-D clippy::needless-as-bytes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_as_bytes)]`
error: could not compile `rustypaste` (lib test) due to 1 previous error
```
> fix(lints): len() can be called directly on strings

- Cargo.lock
- Cargo.toml
- src/random.rs
0.9.0 introduced several (breaking) changes (only listing relevant ones for this change):
- Rename module rand::distributions to rand::distr
- Rename fn rand::thread_rng() to rand::rng() and remove from the prelude
- Deprecate thread_rng()
----
Bumps [rand](https://github.com/rust-random/rand) from 0.8.5 to 0.9.0.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/rust-random/rand/blob/master/CHANGELOG.md">rand's changelog</a>.</em></p>
<blockquote>
<h2>[0.9.0] - 2025-01-27</h2>
<h3>Security and unsafe</h3>
<ul>
<li>Policy: &quot;rand is not a crypto library&quot; (<a href="https://redirect.github.com/rust-random/rand/issues/1514">#1514</a>)</li>
<li>Remove fork-protection from <code>ReseedingRng</code> and <code>ThreadRng</code>. Instead, it is …
> chore(deps): bump rand to 0.9.0

- src/config.rs
- src/main.rs
Use `unsafe` blocks where required by edition 2024.
Edition 2024 requires setting and removing env vars to be in an `unsafe` block.
When switching to edition 2024 in the future, a `cargo fmt` will be required as well.
cargo test
fixtures
> refactor: prepare for rust edition 2024

- .github/workflows/ci.yml
- .lycheeignore
For a while now, 2 links run into a timeout sporadically. I've exluded `repology.org` from the check.
```
[TIMEOUT] https://repology.org/badge/vertical-allrepos/rustypaste.svg | Timeout
[TIMEOUT] https://repology.org/project/rustypaste/versions | Timeout
```
Additionally according to the lychee documentation the exclude argument should be enclosed in single quotes.
I have also escaped the `.`, since we are using a regex.
We could also use a `.lycheeignore` file. e.g. it would make it easier to add complete links to that file, than changing the ci workflow file.
> ci(lychee): add `.lycheeignore` with new links

- cliff.toml
The current template adds `New Contributors` on the same level as the release. It should be on the same level as `Added`, `Changed`, ... It also uses `*` as the list character.
Additionally there is no empty line between the contributors and the release version. 
I've changed the level and used `-` as the list character for consistency. I've also added an empty line for better reading.
```markdown
- @Narayanbhat166 made their first contribution
- @Vaelatern made their first contribution
- @nydragon made their first contribution
```
@orhun maybe you can have a look at the following issues, since you are the git-cliff expert 😉:
1. I wasn't able to fix 2 empty lines when there are no new contributors. But it's still better readable than no empty line if there are new contributors.
2. The `in …
> chore(cliff): fix heading level for new contributors

- Cargo.lock
Bumping actix-service to 2.0.3 removes the `paste` dependency.
closes #415
> chore(deps): bump actix-service to 2.0.3

- CHANGELOG.md
The link was already in the changelog and the new one was missing one character, thus the link pipeline failed....
> docs(changelog): remove superfluous incorrect link

- fixtures/test-fixtures.sh
- fixtures/test-server-upload-dir-limit/test.sh
If the `test-fixtures.sh` script uses an argument, the test will always pass no matter what.
This change fixes the issue.
Additionally, the `test-server-upload-dir-limit` failed for multiple reasons:
- truncate on macOS does not understand `KB`
- curl returns an exit code 23 if you try to output a binary file to the terminal
- bash prints a warning if it encounters a null byte (this does not fail the test, but is still annoying)
P.S.: I still do not understand how the upload_dir_limit test could have ever passed in the pipeline.
> fix(fixtures): script and one test

- README.md
- config.toml
- fixtures/test-file-upload-random-noext/config.toml
- fixtures/test-file-upload-random-noext/test.sh
- src/paste.rs
- src/random.rs
Rustypaste adds the filename's extension to the url. This can be changed by setting `no_extension` to `true`:
```toml
random_url = { type = "alphanumeric", length = 8, no_extension = true }
```
closes #437
see #437
- cargo test
- fixtures
- manual tests
````
- Add option `no_extension` to `random_url` so that no extension is added to the random URL
```toml
random_url = { type = "alphanumeric", length = 8, no_extension = true }
```
````
> feat(server): no extension for random urls

- src/paste.rs
- src/util.rs
found by #446 
fixes:
```
warning: this can be `std::io::Error::other(_)`
--> src/paste.rs:201:26
|
201 |             .map_err(|_| IoError::new(IoErrorKind::Other, String::from("path is not valid")))?;
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error
= note: `#[warn(clippy::io_other_error)]` on by default
help: use `std::io::Error::other`
|
201 -             .map_err(|_| IoError::new(IoErrorKind::Other, String::from("path is not valid")))?;
201 +             .map_err(|_| IoError::other(String::from("path is not valid")))?;
|
warning: this can be `std::io::Error::other(_)`
--> src/paste.rs:286:26
|
286 |             .map_err(|e| …
```
> fix(lints): apply clippy suggestions
